spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Silver1441/spring-cloud-test-config

server:
  port: ${CONFIG_PORT:8888}